# Generated by Django 4.2 on 2023-08-30 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cusform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('team_type', models.CharField(choices=[('team', 'Team'), ('solo', 'Solo'), ('both', 'Team/Solo')], max_length=4)),
                ('team_size', models.IntegerField()),
                ('dept', models.CharField(choices=[('cse', 'Computer Science'), ('ece', 'ECE'), ('eee', 'EEE'), ('mech', 'Mechanical'), ('civil', 'Civil'), ('chem', 'Chemical'), ('it', 'Information Technology'), ('bme', 'Biomedical Engineering')], max_length=5)),
                ('rounds', models.IntegerField()),
                ('venue', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('first_prize', models.IntegerField()),
                ('second_prize', models.IntegerField()),
                ('third_prize', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('bullets', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_rounds', to='cusform.event')),
            ],
        ),
        migrations.CreateModel(
            name='Bullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bullet_point', models.TextField()),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_bullets', to='cusform.round')),
            ],
        ),
    ]
