# Generated by Django 4.2 on 2023-08-30 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cusform', '0002_event_round_bullet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='bullets',
        ),
        migrations.DeleteModel(
            name='Bullet',
        ),
    ]
